/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tia.pruebatecnica.ui;

import com.tia.pruebatecnica.services.ReporteService;
import com.tia.pruebatecnica.utils.AppContextProvider;
import com.tia.pruebatecnica.utils.ExcelGenerator;
import java.awt.Color;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ricardo
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    private void generarReporte() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar reporte como...");
        fileChooser.setSelectedFile(new File("reporte_enemigo.xls"));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            String rutaArchivo = fileChooser.getSelectedFile().getAbsolutePath();
            ReporteService reporteService = AppContextProvider.getBean(ReporteService.class);
            List<Object[]> datos = reporteService.obtenerReporteAgrupado();
            boolean exito = ExcelGenerator.generarReporte(rutaArchivo, datos);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Reporte generado exitosamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al generar el reporte.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    public static void start() {
        SwingUtilities.invokeLater(() -> {
            new MainUI(); // Asegura que se crea una instancia
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        generarPanel = new javax.swing.JPanel();
        generarLabel = new javax.swing.JLabel();
        windowTitleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        estadoServidorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(10, 51, 42));
        setResizable(false);

        background.setBackground(new java.awt.Color(10, 22, 51));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generarPanel.setBackground(new java.awt.Color(255, 255, 255));
        generarPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generarPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                generarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generarPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                generarPanelMousePressed(evt);
            }
        });
        generarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generarLabel.setBackground(new java.awt.Color(255, 255, 255));
        generarLabel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        generarLabel.setForeground(new java.awt.Color(10, 22, 51));
        generarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generarLabel.setText("GENERAR REPORTE");
        generarPanel.add(generarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 50));

        background.add(generarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 210, 50));

        windowTitleLabel.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        windowTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        windowTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        windowTitleLabel.setText("Prueba Técnica TIA S.A");
        background.add(windowTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 910, -1));

        descriptionLabel.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setText("Pulsa en el botón GENERAR REPORTE para descargar el reporte en formato .xls");
        background.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 910, 80));

        estadoServidorLabel.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        estadoServidorLabel.setForeground(new java.awt.Color(240, 240, 240));
        estadoServidorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadoServidorLabel.setText("Servidor corriendo...");
        background.add(estadoServidorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 910, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarPanelMouseClicked
        generarReporte();
    }//GEN-LAST:event_generarPanelMouseClicked

    private void generarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarPanelMouseEntered
        generarPanel.setBackground(new Color(200,200,200));
    }//GEN-LAST:event_generarPanelMouseEntered

    private void generarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarPanelMouseExited
        generarPanel.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_generarPanelMouseExited

    private void generarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarPanelMousePressed
        generarPanel.setBackground(new Color(150,150,150));

    }//GEN-LAST:event_generarPanelMousePressed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel estadoServidorLabel;
    private javax.swing.JLabel generarLabel;
    private javax.swing.JPanel generarPanel;
    private javax.swing.JLabel windowTitleLabel;
    // End of variables declaration//GEN-END:variables
}
